---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  labels:
    app: prometheus
spec:
  storageClassName: monitoring-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
