name: Solidity v1

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - "solidity-v1/**"
      - "!solidity-v1/dashboard/**"
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for workflow execution"
        required: false
        default: "dev"
      upstream_builds:
        description: "Upstream builds"
        required: false
      upstream_ref:
        description: "Git reference to checkout (e.g. branch name)"
        required: false
        default: "main"

jobs:
  contracts-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'

      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './solidity-v1/!(dashboard)/**'

  contracts-build-and-test:
    needs: contracts-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: solidity-v1/package-lock.json

      # This step forces Git to download dependencies using `https://` protocol,
      # even if `package-lock.json` refers to some package via `git://`. Using
      # `git://` is no longer supported by GH.
      - name: Configure git to don't use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: npm ci

      - name: Build solidity contracts
        run: npm run compile

      - name: Run tests
        run: npm run test

  contracts-lint:
    needs: contracts-detect-changes
    if: |
      github.event_name == 'push'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: solidity-v1/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  contracts-migrate-and-publish:
    needs: [contracts-build-and-test]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    outputs:
      version: ${{ steps.npm-version-bump.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Load environment variables
        uses: keep-network/ci/actions/load-env-variables@v1
        with:
          environment: ${{ github.event.inputs.environment }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: solidity-v1/package-lock.json
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Migrate contracts on Ethereum
        if: github.event.inputs.environment != 'alfajores'
        env:
          CHAIN_API_URL: ${{ secrets.KEEP_TEST_ETH_HOSTNAME_WS }}
          CONTRACT_OWNER_ACCOUNT_PRIVATE_KEY: |
            ${{ secrets.KEEP_TEST_ETH_CONTRACT_OWNER_PRIVATE_KEY }}
        run: npx truffle migrate --reset --network $TRUFFLE_NETWORK

      - name: Copy artifacts
        run: |
          mkdir -p artifacts
          cp -r build/contracts/* artifacts/

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          work-dir: ./solidity-v1
          environment: ${{ github.event.inputs.environment }}
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Push contracts to Tenderly
        if: github.event.inputs.environment == 'ropsten'
        uses: keep-network/tenderly-push-action@v1
        continue-on-error: true
        with:
          working-directory: ./solidity-v1
          tenderly-token: ${{ secrets.TENDERLY_TOKEN }}
          tenderly-project: thesis/keep-test
          eth-network-id: ${{ env.NETWORK_ID }}
          github-project-name: keep-core
          version-tag: ${{ steps.npm-version-bump.outputs.version }}

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access=public --tag ${{ github.event.inputs.environment }}

      - name: Upload keep-core contracts for initcontainer build
        uses: actions/upload-artifact@v2
        with:
          name: Contracts
          path: ./solidity-v1/build/contracts/*

      - name: Upload files needed for etherscan verification
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts for etherscan verifcation
          path: |
            ./solidity-v1/build
            ./solidity-v1/package.json
            ./solidity-v1/package-lock.json

  contracts-build-and-publish-initcontainer:
    needs: [contracts-migrate-and-publish]
    if: needs.contracts-migrate-and-publish.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load environment variables
        uses: keep-network/ci/actions/load-env-variables@v1
        with:
          environment: ${{ github.event.inputs.environment }}

      - name: Download migrated contracts artifacts
        uses: actions/download-artifact@v2
        with:
          name: Contracts
          path: ./infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GCR_REGISTRY_URL }}
          username: _json_key
          password: ${{ secrets.KEEP_TEST_GCR_JSON_KEY }}

      - name: Build and publish initcontainer
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: initcontainer-provision-keep-client-${{ env.CHAIN }}
        with:
          context: ./infrastructure/kube/templates/keep-client/initcontainer/provision-keep-client/
          # GCR image should be named according to following convention:
          # HOSTNAME/PROJECT-ID/IMAGE:TAG
          # We don't use TAG yet, will be added at later stages of work on RFC-18.
          tags: ${{ env.GCR_REGISTRY_URL }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}
          labels: |
            revision=${{ github.sha }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Notify CI about completion of the workflow
        uses: keep-network/ci/actions/notify-workflow-completed@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          module: "github.com/keep-network/keep-core/solidity-v1"
          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          environment: ${{ github.event.inputs.environment }}
          upstream_builds: ${{ github.event.inputs.upstream_builds }}
          upstream_ref: ${{ github.event.inputs.upstream_ref }}
          version: ${{ needs.contracts-migrate-and-publish.outputs.version }}

      - # Temp fix - move cache instead of copying (added below step and
        # modified value of `cache-to`).
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        # Without the change some jobs were failing with `no space left on device`
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  contracts-etherscan-verification:
    needs: [contracts-migrate-and-publish]
    if: github.event.inputs.environment != 'alfajores'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    steps:
      - uses: actions/checkout@v3

      - name: Download files needed for etherscan verification
        uses: actions/download-artifact@v2
        with:
          name: Artifacts for etherscan verifcation
          path: ./solidity-v1

      - name: Load environment variables
        uses: keep-network/ci/actions/load-env-variables@v1
        with:
          environment: ${{ github.event.inputs.environment }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: solidity-v1/package-lock.json

      - name: Install needed dependencies
        run: npm ci

      - name: Verify Ethereum contracts on Etherscan
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          TRUFFLE_NETWORK: ${{ env.TRUFFLE_NETWORK}}
        run: ./scripts/etherscan-verify.sh
