name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  pull_request:
  workflow_dispatch:

jobs:
  docs-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './docs/**'

  docs-html:
    runs-on: ubuntu-latest
    needs: docs-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.docs-detect-changes.outputs.path-filter == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Build HTML docs
        id: html
        uses: thesis/asciidoctor-action@v1.1
        with:
          files: 'docs/*.adoc docs/**/*.adoc'
          args: '-a revdate=`date +%Y-%m-%d` --failure-level=ERROR'

      # A push event is a main merge; deploy to primary bucket.
      - if: github.event_name == 'push'
        name: Upload asciidocs
        uses: thesis/gcp-storage-bucket-action@v3.1.0
        with:
          service-key: ${{ secrets.DOCS_KEEP_NETWORK_UPLOADER_SERVICE_KEY_JSON }}
          project: cfc-production
          bucket-name: docs.keep.network
          bucket-path: .
          build-folder: ${{ steps.html.outputs.asciidoctor-artifacts }}/docs

      # A pull_request event is a PR; deploy to preview bucket.
      - if: github.event_name == 'pull_request'
        name: Upload asciidocs preview
        uses: thesis/gcp-storage-bucket-action@v3.1.0
        with:
          service-key: ${{ secrets.DOCS_KEEP_NETWORK_UPLOADER_SERVICE_KEY_JSON }}
          project: cfc-production
          bucket-name: docs.keep.network
          bucket-path: ${{ github.head_ref }}
          build-folder: ${{ steps.html.outputs.asciidoctor-artifacts }}/docs
